version: '3.6'
services:
  neo4j:
    image: neo4j:5.3.0
    container_name: pocas_neo
    volumes:
      - 'neo_data:/data'
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    env_file:
      - .env
    networks:
      - graph_net

volumes:
  neo_data:

networks:
  graph_net:
    driver: bridge