version: '3.6'
services:
  mongo_db:
    container_name: pocas_mongo
    image: mongo
    volumes:
      - mongo_db:/data/db
    restart: always
    env_file:
      - local.env
    ports:
      - 27017:27017


  api:
    container_name: pocas_api
    build:
      context: ./
      dockerfile: Dockerfile_Python
    command: python api/app.py
    ports:
      - 8080:80
    env_file:
      - local.env
      - keys.env

# TODO: init script to upload to mongo
# TODO: Add nginx
# TODO: Add oauth. or nginx
# TODO: send questionaire and then create return of lat/lon and things to use

volumes:
  mongo_db: