FROM python:3.7

RUN apt-get update && apt-get install -y \
    git \
    apt-utils \
    build-essential

RUN mkdir /app
COPY requirements.txt /app/
WORKDIR /app
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
ENV PYTHONPATH /app

COPY app /app
