version: '3.6'
services:
  mongo_db:
    container_name: pocas_mongo
    image: mongo
    volumes:
      - mongo_db:/data/db
    restart: always
    env_file:
      - local.env
    ports:
      - 27017:27017


  api:
    container_name: pocas_api
    build:
      context: ./
      dockerfile: Dockerfile_Python
#    command: python api/app.py
    volumes:
      - ./data:/data
    ports:
      - 8080:8080
    env_file:
      - local.env
      - keys.env
      - api.env

volumes:
  mongo_db: