FROM tiangolo/uwsgi-nginx-flask:python3.7

RUN apt-get update && apt-get install -y \
    git \
    apt-utils \
    build-essential

COPY requirements.txt /app/
WORKDIR /app
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY app /app
