version: '3.6'
services:
  mongo_db:
    container_name: pocas_mongo
    image: mongo
    volumes:
      - mongo_db:/data/db
    restart: always
    networks:
      - pocas_net
    env_file:
      - local.env

  api:
    container_name: pocas_api
    depends_on:
      - mongo_db
    build:
      context: ./
      dockerfile: Dockerfile_API
    volumes:
      - ./data:/data
    networks:
      - pocas_net
    env_file:
      - local.env
      - keys.env
      - api.env
  admin:
    container_name: pocas_admin
    depends_on:
      - mongo_db
    build:
      context: ./
      dockerfile: DockerFile_ADMIN
    networks:
      - pocas_net
    env_file:
      - local.env
      - keys.env
      - api.env

  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./c/certbot/conf:/etc/letsencrypt
      - ./c/certbot/www:/var/www/certbot
    depends_on:
      - frontend
    networks:
      - pocas_net
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./c/certbot/conf:/etc/letsencrypt
      - ./c/certbot/www:/var/www/certbot
    depends_on:
      - nginx
    command: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  frontend:
    container_name: frontend
    restart: always
    depends_on:
      - postgres
      - mongo_db
      - api
    environment:
      - WORKERS_PER_CORE=0.5
    build:
      context: ./
      dockerfile: DockerFile_UI
    networks:
      - pocas_net
    env_file:
      - .env
      - keys.env
      - api.env
      - local.env

  postgres:
    container_name: postgresdb
    image: postgres:14.1
    restart: always
    env_file:
      - .env
    networks:
      -   pocas_net
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  mongo_db:
  postgres_db:

networks:
  pocas_net:
    driver: bridge