"""Descriptions"""
# pylint: disable=C0302
descriptions = [
    "Sponsoring support groups each month designed to meet the needs of the community"
    " and each individual.\nAdvocating for equal treatment and equal opportunity for"
    " all transgender people through education and training.\nSince 1998 the Arizona"
    " Transgender Workplace Project (ATWork)  has been instrumental in helping"
    " employers create more transgender inclusive workplaces.\nBeing the primary"
    " resource for information on transgender issues in the Southwest.\nInformation and"
    " Referral database of trans-friendly businesses, service providers, doctors and"
    " other resources.\nID and Documentation Assistance to help navigate the"
    " complicated process of updating documents to reflect new name and gender",
    "\nHomeless Families\nWhen a family is experiencing homelessness, Our Family"
    " Services is a point of entry for them to launch their fresh start.\n\nHomeless"
    " Youth\nWhen a young person engages with Our Family staff, they receive"
    " comprehensive services that meet their unique needs.\n\nReunion House\nWe are"
    " proud of our Reunion House shelter—a crisis shelter for abused, homeless, and"
    " runaway teens (ages 12 – 17); it’s the only shelter of its kind in all of"
    " Southern Arizona.\n\nInformation & Referral\nThrough the I&R directory, 2-1-1"
    " helpline, and online portal, anyone in our community can easily connect with"
    " thousands of resources.\n",
    "\nCover Arizona is a coalition of more than 900 members statewide that is"
    " committed to increasing health coverage. We are engaged building awareness of"
    " opportunities available through the Health Insurance Marketplace and AHCCCS,"
    " Arizona’s Medicaid.   Members are actively engaged in local outreach activities,"
    " and are committed to ensuring that trained enrollment assisters are available for"
    " consumers seeking coverage.\n",
    "\nThe Supplemental Nutrition Program for Women, Infants, and Children (WIC)"
    " provides nutrition education, breastfeeding support, supplemental nutritious"
    " foods and referrals to health and social services.\nElderly Simplified"
    " Application Project Image\nELDERLY SIMPLIFIED APPLICATION PROJECT\nSimplified"
    " Nutrition Assistance application for persons age 60 or older who have no earned"
    " income.\nCommunity Assistor Image\nCOMMUNITY ASSISTOR\nTrained Community Partners"
    " that Help Individuals and Families Connect to Coverage, Benefits and"
    " Services.\n\n",
    "\nALTCS (pronounced ALTECS) is an acronym for the Arizona Long Term Care System."
    " ALTCS is an Arizona Medicaid program that is designed to help fixed income"
    " seniors and other disabled individuals afford the care that they need. ALTCS pays"
    " for the care that you need after savings are exhausted. The program requires an"
    " application and typically takes between 60 and 90 days for approval. We are not"
    " the governmental ALTCS Medicaid office, but Senior Planning is happy to assist"
    " you through the application process along with finding care.\n\nALTCS"
    " Eligibility\nbbb\nThe Arizona Long Term Care program is for seniors and disabled"
    " individuals that need long term care. There are two components to the"
    " application. The first is a financial assessment, determining whether or not the"
    " applicant can afford to pay for necessary care on their own. We are happy to go"
    " over your specific financial situation to determine whether or not you qualify."
    " The second component is the functional and medical assessment, which determines"
    " whether a person is truly in need of long term care. Total need is determined by"
    " points with a successful application scoring 60 points or higher.\n\nFinding"
    " ALTCS Providers\nSenior Planning will also help you find the care you need,"
    " sometimes even when you are still waiting for the ALTCS application to go"
    " through. Senior Planning will work with you to determine what kind of care you"
    " need and what care solution will work best for you.\n\nFree Services\nSenior"
    " Planning is paid commission for the care services that we find. We do not charge"
    " our clients for consultations about the ALTCS application or finding care for"
    " you. We are paid a commission by the communities so finding care is free to you."
    " We also offer more robust services for benefits assistance at extremely"
    " affordable rates.\n",
    "\nKidsCare (Arizona’s Children’s Health Insurance Program) provides health"
    " coverage for children under age 19 who do not qualify for AHCCCS. Monthly costs"
    " start as low as $10.\n",
    "\nThe Qualified Medicare Beneficiary program (QMB), Specified Low-Income Medicare"
    " Beneficiary program (SLMB), and Qualified Individual program (QI), help Medicare"
    " beneficiaries of modest means pay all or some of Medicare’s cost sharing amounts"
    " (ie. premiums, deductibles and copayments). To qualify an individual must be"
    " eligible for Medicare and must meet certain income guidelines which change"
    " annually. The income guidelines, which are based on the Federal Poverty Level,"
    " change April 1 each year and can be found here.\n",
    "\nSince 1967, PCOA has led the way to improve the experience of aging for the"
    " communities of Pima County, Arizona. Providing expert services, advocacy, and"
    " unbiased information for older people and their families is at the heart of our"
    " work.\n\nPCOA is a nonprofit organization dedicated to inclusive, innovative, and"
    " integrated services that meet the changing needs of Pima County’s older adults."
    " This work is only possible with the support of our funders, donors, and"
    " volunteers.\n\nPCOA helps our community age well through a network of programs"
    " and services, provided directly by our knowledgeable staff and volunteers, or"
    " offered through agreements with community partners.\n\nIn everything we do, we"
    " advocate for the rights and needs of older adults. We provide resources and"
    " information to help you make informed choices and find solutions that are right"
    " for you. And we offer education and services to help you live an independent,"
    " vibrant life.\n\n",
    "\nWho We Serve\nEach year the Mobile Health Program provides patient services to"
    " about 2,400 persons in southern Arizona where little or no health care services"
    " are available. No one is turned away regardless of ability to pay for services."
    " The Program primarily provides services to the medically underserved or uninsured"
    " people of southern Arizona. The program provides basic wellness and preventive"
    " care for people with acute and chronic conditions. The MHP also has the capacity"
    " to do diabetes education via telemedicine and diabetic retinopathy screening"
    " using a non mydriatic camera. This program uses state-of-the-art technology,"
    " including telemedicine to provide blindness prevention services to uninsured"
    " people with diabetes. Since 2003, approximately 225 uninsured women have received"
    " prenatal care for the whole family in an innovative Group Prenatal Care project;"
    " this is a cost-effective way to provide excellent prenatal care to women and"
    " their babies who might otherwise receive none. In collaboration with Family"
    " Medicine residents and faculty from the UA College of Medicine, the MHP staff"
    " provides prenatal care, counseling and prenatal and postpartum health education."
    " Pregnant mothers will deliver at the Banner University Medical Center. \n\nWhere"
    " We Serve\nEach project or program serves specific areas of southern Arizona, from"
    " rural areas to low income urban areas. The communities served include, the Old"
    " Nogales Highway Colonia or Summit View, and underserved communities within the"
    " city of Tucson including Littletown, Elvira, and Banks Elementary.\n",
    "\nWho is WIC for?\nBreastfeeding women\nChildren (under age"
    " 5)\nInfants\nPostpartum women\nPregnant women\nWhat does WIC"
    " provide?\nBreastfeeding Support\nHealthy Foods\nNutrition Information\nReferrals"
    " to Health care and other social services\n\n",
    "\nWho is WIC for?\nBreastfeeding women\nChildren (under age"
    " 5)\nInfants\nPostpartum women\nPregnant women\nWhat does WIC"
    " provide?\nBreastfeeding Support\nHealthy Foods\nNutrition Information\nReferrals"
    " to Health care and other social services\n",
    "\nWho is WIC for?\nBreastfeeding women\nChildren (under age"
    " 5)\nInfants\nPostpartum women\nPregnant women\nWhat does WIC"
    " provide?\nBreastfeeding Support\nHealthy Foods\nNutrition Information\nReferrals"
    " to Health care and other social services\n",
    "\nWho is WIC for?\nBreastfeeding women\nChildren (under age"
    " 5)\nInfants\nPostpartum women\nPregnant women\nWhat does WIC"
    " provide?\nBreastfeeding Support\nHealthy Foods\nNutrition Information\nReferrals"
    " to Health care and other social services\n",
    "\nWho is WIC for?\nBreastfeeding women\nChildren (under age"
    " 5)\nInfants\nPostpartum women\nPregnant women\nWhat does WIC"
    " provide?\nBreastfeeding Support\nHealthy Foods\nNutrition Information\nReferrals"
    " to Health care and other social services\n",
    "\nWho is WIC for?\nBreastfeeding women\nChildren (under age"
    " 5)\nInfants\nPostpartum women\nPregnant women\nWhat does WIC"
    " provide?\nBreastfeeding Support\nHealthy Foods\nNutrition Information\nReferrals"
    " to Health care and other social services\n",
    "\nWho is WIC for?\nBreastfeeding women\nChildren (under age"
    " 5)\nInfants\nPostpartum women\nPregnant women\nWhat does WIC"
    " provide?\nBreastfeeding Support\nHealthy Foods\nNutrition Information\nReferrals"
    " to Health care and other social services\n",
    "\n\nCounseling & Wellness\n\nDental Care\n\nFamily"
    " Practice\n\nOutreach\n\nPharmacy Services\n\nWIC Program\n\nPediatrics\n",
    "\nWelcome to the Arizona Department of Economic Security (DES). DES works with"
    " families, community organizations, advocates and state and federal partners to"
    " realize our collective vision that every child, adult, and family in Arizona will"
    " be safe and economically secure.\n\nDES works to promote enhanced safety and"
    " well-being for Arizonans by focusing on three primary goals:\n\nStrengthening"
    " individuals and families;\nIncreasing self-sufficiency; and,\nDeveloping the"
    " capacity of communities.\nWhether you are an individual who needs help, a"
    " potential employee passionate about helping others, or a part of the extensive"
    " network of human service professionals throughout Arizona dedicated to improving"
    " outcomes for children and families, we look forward to working with you to create"
    " a better tomorrow by providing support today.\n\n",
    "\nWelcome to the Arizona Department of Economic Security (DES). DES works with"
    " families, community organizations, advocates and state and federal partners to"
    " realize our collective vision that every child, adult, and family in Arizona will"
    " be safe and economically secure.\n\nDES works to promote enhanced safety and"
    " well-being for Arizonans by focusing on three primary goals:\n\nStrengthening"
    " individuals and families;\nIncreasing self-sufficiency; and,\nDeveloping the"
    " capacity of communities.\nWhether you are an individual who needs help, a"
    " potential employee passionate about helping others, or a part of the extensive"
    " network of human service professionals throughout Arizona dedicated to improving"
    " outcomes for children and families, we look forward to working with you to create"
    " a better tomorrow by providing support today.\n\n",
    "\nWelcome to the Arizona Department of Economic Security (DES). DES works with"
    " families, community organizations, advocates and state and federal partners to"
    " realize our collective vision that every child, adult, and family in Arizona will"
    " be safe and economically secure.\n\nDES works to promote enhanced safety and"
    " well-being for Arizonans by focusing on three primary goals:\n\nStrengthening"
    " individuals and families;\nIncreasing self-sufficiency; and,\nDeveloping the"
    " capacity of communities.\nWhether you are an individual who needs help, a"
    " potential employee passionate about helping others, or a part of the extensive"
    " network of human service professionals throughout Arizona dedicated to improving"
    " outcomes for children and families, we look forward to working with you to create"
    " a better tomorrow by providing support today.\n\n",
    "\nWelcome to the Arizona Department of Economic Security (DES). DES works with"
    " families, community organizations, advocates and state and federal partners to"
    " realize our collective vision that every child, adult, and family in Arizona will"
    " be safe and economically secure.\n\nDES works to promote enhanced safety and"
    " well-being for Arizonans by focusing on three primary goals:\n\nStrengthening"
    " individuals and families;\nIncreasing self-sufficiency; and,\nDeveloping the"
    " capacity of communities.\nWhether you are an individual who needs help, a"
    " potential employee passionate about helping others, or a part of the extensive"
    " network of human service professionals throughout Arizona dedicated to improving"
    " outcomes for children and families, we look forward to working with you to create"
    " a better tomorrow by providing support today.\n\n",
    "\nWelcome to the Arizona Department of Economic Security (DES). DES works with"
    " families, community organizations, advocates and state and federal partners to"
    " realize our collective vision that every child, adult, and family in Arizona will"
    " be safe and economically secure.\n\nDES works to promote enhanced safety and"
    " well-being for Arizonans by focusing on three primary goals:\n\nStrengthening"
    " individuals and families;\nIncreasing self-sufficiency; and,\nDeveloping the"
    " capacity of communities.\nWhether you are an individual who needs help, a"
    " potential employee passionate about helping others, or a part of the extensive"
    " network of human service professionals throughout Arizona dedicated to improving"
    " outcomes for children and families, we look forward to working with you to create"
    " a better tomorrow by providing support today.\n\n",
    "\nWelcome to the Arizona Department of Economic Security (DES). DES works with"
    " families, community organizations, advocates and state and federal partners to"
    " realize our collective vision that every child, adult, and family in Arizona will"
    " be safe and economically secure.\n\nDES works to promote enhanced safety and"
    " well-being for Arizonans by focusing on three primary goals:\n\nStrengthening"
    " individuals and families;\nIncreasing self-sufficiency; and,\nDeveloping the"
    " capacity of communities.\nWhether you are an individual who needs help, a"
    " potential employee passionate about helping others, or a part of the extensive"
    " network of human service professionals throughout Arizona dedicated to improving"
    " outcomes for children and families, we look forward to working with you to create"
    " a better tomorrow by providing support today.\n\n",
    "\nWelcome to the Arizona Department of Economic Security (DES). DES works with"
    " families, community organizations, advocates and state and federal partners to"
    " realize our collective vision that every child, adult, and family in Arizona will"
    " be safe and economically secure.\n\nDES works to promote enhanced safety and"
    " well-being for Arizonans by focusing on three primary goals:\n\nStrengthening"
    " individuals and families;\nIncreasing self-sufficiency; and,\nDeveloping the"
    " capacity of communities.\nWhether you are an individual who needs help, a"
    " potential employee passionate about helping others, or a part of the extensive"
    " network of human service professionals throughout Arizona dedicated to improving"
    " outcomes for children and families, we look forward to working with you to create"
    " a better tomorrow by providing support today.\n\n",
    "\nWelcome to the Arizona Department of Economic Security (DES). DES works with"
    " families, community organizations, advocates and state and federal partners to"
    " realize our collective vision that every child, adult, and family in Arizona will"
    " be safe and economically secure.\n\nDES works to promote enhanced safety and"
    " well-being for Arizonans by focusing on three primary goals:\n\nStrengthening"
    " individuals and families;\nIncreasing self-sufficiency; and,\nDeveloping the"
    " capacity of communities.\nWhether you are an individual who needs help, a"
    " potential employee passionate about helping others, or a part of the extensive"
    " network of human service professionals throughout Arizona dedicated to improving"
    " outcomes for children and families, we look forward to working with you to create"
    " a better tomorrow by providing support today.\n\n",
    "\nWelcome to the Arizona Department of Economic Security (DES). DES works with"
    " families, community organizations, advocates and state and federal partners to"
    " realize our collective vision that every child, adult, and family in Arizona will"
    " be safe and economically secure.\n\nDES works to promote enhanced safety and"
    " well-being for Arizonans by focusing on three primary goals:\n\nStrengthening"
    " individuals and families;\nIncreasing self-sufficiency; and,\nDeveloping the"
    " capacity of communities.\nWhether you are an individual who needs help, a"
    " potential employee passionate about helping others, or a part of the extensive"
    " network of human service professionals throughout Arizona dedicated to improving"
    " outcomes for children and families, we look forward to working with you to create"
    " a better tomorrow by providing support today.\n\n",
    "\nWelcome to the Arizona Department of Economic Security (DES). DES works with"
    " families, community organizations, advocates and state and federal partners to"
    " realize our collective vision that every child, adult, and family in Arizona will"
    " be safe and economically secure.\n\nDES works to promote enhanced safety and"
    " well-being for Arizonans by focusing on three primary goals:\n\nStrengthening"
    " individuals and families;\nIncreasing self-sufficiency; and,\nDeveloping the"
    " capacity of communities.\nWhether you are an individual who needs help, a"
    " potential employee passionate about helping others, or a part of the extensive"
    " network of human service professionals throughout Arizona dedicated to improving"
    " outcomes for children and families, we look forward to working with you to create"
    " a better tomorrow by providing support today.\n\n",
    "\nWelcome to the Arizona Department of Economic Security (DES). DES works with"
    " families, community organizations, advocates and state and federal partners to"
    " realize our collective vision that every child, adult, and family in Arizona will"
    " be safe and economically secure.\n\nDES works to promote enhanced safety and"
    " well-being for Arizonans by focusing on three primary goals:\n\nStrengthening"
    " individuals and families;\nIncreasing self-sufficiency; and,\nDeveloping the"
    " capacity of communities.\nWhether you are an individual who needs help, a"
    " potential employee passionate about helping others, or a part of the extensive"
    " network of human service professionals throughout Arizona dedicated to improving"
    " outcomes for children and families, we look forward to working with you to create"
    " a better tomorrow by providing support today.\n\n",
    "\nWelcome to the Arizona Department of Economic Security (DES). DES works with"
    " families, community organizations, advocates and state and federal partners to"
    " realize our collective vision that every child, adult, and family in Arizona will"
    " be safe and economically secure.\n\nDES works to promote enhanced safety and"
    " well-being for Arizonans by focusing on three primary goals:\n\nStrengthening"
    " individuals and families;\nIncreasing self-sufficiency; and,\nDeveloping the"
    " capacity of communities.\nWhether you are an individual who needs help, a"
    " potential employee passionate about helping others, or a part of the extensive"
    " network of human service professionals throughout Arizona dedicated to improving"
    " outcomes for children and families, we look forward to working with you to create"
    " a better tomorrow by providing support today.\n\n",
    "\nThe Social Security Administration assigns Social Security numbers, and"
    " administers the Social Security retirement, survivors, and disability insurance"
    " programs. They also administer the Supplemental Security Income program for the"
    " aged, blind, and disabled.\n",
    "\nThe Social Security Administration assigns Social Security numbers, and"
    " administers the Social Security retirement, survivors, and disability insurance"
    " programs. They also administer the Supplemental Security Income program for the"
    " aged, blind, and disabled.\n",
    "\nThe goal of the social services department is to promote the self-sufficiency of"
    " the American Indian people through education, leadership opportunities and"
    " employment resources and referrals. The Tucson Indian Center believes that the"
    " basic needs of American Indian people and families must be met so we as a"
    " community are able to pursue a healthy and happy quality of life.\n\nThe Social"
    " Services Department offers an array of services and programs geared primarily to"
    " employment, community involvement, leadership development, on the job training"
    " and emergency housing assistance. Throughout a comprehensive, accessible, and"
    " high-quality workforce development program the Tucson Indian Centers has been"
    " providing to Urban America Indian’s workers and jobseekers across the Tucson"
    " Metropolitan Area, with the skills and credentials necessary to secure, retain"
    " and advance in employment.\nThe Tucson Indian Center’s Health Services Department"
    " is committed to providing the Tucson urban American Indian community and others"
    " with the following services in response to the COVID-19 pandemic and in"
    " partnership with our valuable partners such as Pima County Health Department,"
    " Tohono O’Odham Nation, Pascua Yaqui Tribe, Indian Health Services, and University"
    " of Arizona Mobile Health Program and"
    " MEZCOPH:\n\nVaccines\nBoosters\nTesting\nTransportation\nCare packages & COVID-19"
    " supplies\nQuarantine support\nEducation\nDaily welfare checks\nCase"
    " Management\n\nPersonalized assessment of health and wellness needs and"
    " strengths\nCase management services for access and utilization of health and"
    " wellness services\nHealth education and guidance\nReferrals to other services,"
    " including social services and health services\nSpecialty areas include:\n–"
    " American Indian health and wellness care \n– Substance abuse treatment and"
    " support services \n– Diabetes prevention services, especially addressing"
    " dietician and nutrition, physical activity, weight management, podiatry and eye"
    " exam/glasses.\n",
    "\nThe Community and Workforce Development (CWD) department connects individuals,"
    " families, neighborhoods, businesses and community based organizations to a"
    " network of resources, supports and services essential for learning, working, "
    " living and thriving in Pima  County. The CWD team serves with heart, urgency and"
    " in partnership with our community. Help begins with One-Stop.\n",
    "\nThe Community and Workforce Development (CWD) department connects individuals,"
    " families, neighborhoods, businesses and community based organizations to a"
    " network of resources, supports and services essential for learning, working, "
    " living and thriving in Pima  County. The CWD team serves with heart, urgency and"
    " in partnership with our community. Help begins with One-Stop.\n",
    "\nWIC ARIZONA\nThe Supplemental Nutrition Program for Women, Infants, and Children"
    " (WIC) provides nutrition education, breastfeeding support, supplemental"
    " nutritious foods and referrals to health and social services.\nElderly Simplified"
    " Application Project Image\nELDERLY SIMPLIFIED APPLICATION PROJECT\nSimplified"
    " Nutrition Assistance application for persons age 60 or older who have no earned"
    " income.\nCommunity Assistor Image\nCOMMUNITY ASSISTOR\nTrained Community Partners"
    " that Help Individuals and Families Connect to Coverage, Benefits and Services.\n",
    "\nThe Arizona Community Action Association (ACAA) was incorporated as a non-profit"
    " organization in 1967 in response to a need for a statewide forum to address"
    " issues relating to poverty. Through its membership, ACAA has the capability to"
    " bring together public officials, low-income persons, representatives of the"
    " private sector and human service providers to develop strategies to that address"
    " poverty. ACAA was created to:\n\nProvide a unified voice in the fight against"
    " poverty.\nEducate and advocate on behalf of Arizona's low-income"
    " population.\nProvide services that improve the lives of people through self"
    " sufficiency.\nServe as an umbrella organization for local community action"
    " agencies.\n\n",
    "\nBenefitsCheckUp® is the nation’s most comprehensive online tool to connect older"
    " adults and people with disabilities to benefits. We'll make it easy to see if you"
    " may be eligible—and then help you find out where to apply online or how to get"
    " help from a benefits counselor.\n",
    "\nThe 2-1-1 Arizona Information and Referral Services program was founded in 1964"
    " as Community Information and Referral Services and incorporated as a private,"
    " nonprofit 501(c)(3) organization in 1979. Solari acquired the program in"
    " 2017.\n\n2-1-1 Arizona Information and Referral Service operates 24 hours per"
    " day, seven days per week and every day of the year. Live-operator service is"
    " available at all times in English and Spanish and assistance is available in"
    " other languages via real-time interpreter services.\n\n2-1-1 Arizona operators"
    " will help individuals and families find resources that are available to them"
    " locally, throughout the state, and provide connections to critical services that"
    " can improve – and save – lives, including:\n\nSupplemental Food and Nutrition"
    " Programs\nShelter and Housing Options\nUtilities Assistance\nEmergency"
    " Information and Disaster Relief\nEmployment and Education Opportunities\nServices"
    " for Veterans\nHealthcare, vaccination and health epidemic information\nAddiction"
    " Prevention and Rehabilitation Programs\nRe-entry help for ex-offenders\nSupport"
    " groups for individuals with mental illnesses or special needs\nA safe,"
    " confidential path out of physical and/or emotional domestic violence\n",
    "\nTucson Alliance for Autism conducts comprehensive evaluations of ASD that"
    " include a direct interactive assessment of the client and extensive developmental"
    " history and historical perspective from parents.  Evaluations are conducted by a"
    " licensed psychologist and licensed clinical social worker with several decades of"
    " combined experience.  \n\nSOCIAL THINKING/SOCIAL COMMUNICATION GROUPS\nSocial"
    " Thinking/Social Communication groups address how one builds their ability to"
    " engage and negotiate the social interactions essential in everyday life."
    " Meetings, which are facilitated by licensed, certified professionals, help"
    " participants explore/understand perspective taking (the ability to understand"
    " another person’s point of view) as well as developing strategies to address"
    " breakdowns in communication.  \n\n To promote community awareness and provide"
    " diagnostic and therapeutic services for individuals with an Autism Spectrum"
    " Disorder (ASD); to educate and support professionals and families on ASD-related"
    " issues; to support and provide resources for families; to stimulate research and"
    " represent the best interests of the autism community in Tucson and its"
    " surrounding areas.\n",
    "\nEasterseals is leading the way to full equity, inclusion, and access by"
    " enriching education, enhancing health, expanding employment, and elevating"
    " community.\n\nWe do this through life-changing services and on-the-ground"
    " supports for children and adults with disabilities, families, and local"
    " communities across the country.\n\nHelpful Topics\nAutism\nEmployment & Job"
    " Training\nMental Health Services\nTherapy & Rehabilitative"
    " Care\nTransportation\nShow Me Services For\nChildren & Families\nEarly"
    " Intervention\nChild Development Screening Tool\nInclusive Child Care\nEarly"
    " Childhood Education\nCamp & Recreation\nFamily Support &"
    " Resources\nAdults\nEmployment & Job Training\nYouth & Transition\nIn-Home"
    " Care\nAdult Day Services\nCamp & Recreation\nTransportation\nSeniors\nEmployment"
    " for Seniors\nIn-Home Care\nAdult Day Services\nTherapy & Rehabilitative"
    " Care\nTransportation\nVeterans\nResources For Veterans\nMilitary & Veteran"
    " Caregivers\nCaregivers\nCaregiving Services\nRespite Services\n",
    "\nChild Find has three parts:\n\npublic relations\nthe screening process of"
    " locating and identifying those children in need of services\nthe referral of"
    " birth to age 3 children to AzEIP\nWhy evaluate preschool children?\nWhen learning"
    " challenges are identified at a young age, early intervention can help the child"
    " with their development.\n\nWhat to watch for...\nChildren who are showing"
    " difficulties with any of the following areas may have a learning challenge. Watch"
    " for difficulties"
    " with:\n\nspeaking/understanding\nvision\nhearing\nwalking/running\nself-help"
    " skills\nbehavior/social skills\nmanipulating small"
    " objects/drawing\ncognitions/academics\n",
    "\nRaising Special Kids exists to improve the lives of children with the full range"
    " of disabilities, from birth to age 26, by providing support, training,"
    " information and individual assistance so families can become effective advocates"
    " for their children.\n",
    "\nWe are committed to providing encouragement and support to families who have"
    " children with special needs. Available services include:\n\nADVOCACY TRAINING"
    " (Partners in Leadership) – a leadership training program for parents of children"
    " with disabilities and for young adults with disabilities who want to further"
    " themselves as self-advocates.\nAll of our programs and services are offered free"
    " of charge without regard of the child’s disabilities, age, family income,"
    " qualifying conditions or other eligibility factors.\n",
    "\nEveryone deserves the power to live a meaningful life. Unfortunately, structural"
    " inequities create barriers for too many, closing off opportunities and fueling"
    " injustice. Our programs give individuals and families a seat at the table. We"
    " facilitate growth through five Areas of Impact:\n\nHealth & Human"
    " Services\nHousing\nEducation\nEconomic Development\nAdvocacy\nChicanos Por La"
    " Causa (CPLC) formed in 1969 to fight discrimination against the Mexican American"
    " community. Inspired by Dolores Huerta and Cesar Chavez, we advocated for equity"
    " in education, politics, and labor conditions. Today, CPLC provides services to"
    " people of all backgrounds while honoring our Mexican-American roots.\nWith"
    " offices in Arizona, California, Nevada, New Mexico, and Texas, we impact more"
    " than 2 million lives every year.\n",
    "\nThe City of Tucson provides many Housing Assistance programs for our citizens."
    " Below are listed just a few.\n\nHome Owner Programs\nAffordable Housing"
    " Opportunities\nHomelessness\n",
    "\nThe HCV program assists eligible low-income families or individuals in obtaining"
    " affordable, decent, sanitary, and safe housing in Tucson. Rent is based on the"
    " household's income. The portion of rent paid by the Housing Authority is paid"
    " directly to the landlord and the participant pays the difference of the contract"
    " rent to the landlord directly.\n",
    "\nThe HCV program assists eligible low-income families or individuals in obtaining"
    " affordable, decent, sanitary, and safe housing in Tucson. Rent is based on the"
    " household's income. The portion of rent paid by the Housing Authority is paid"
    " directly to the landlord and the participant pays the difference of the contract"
    " rent to the landlord directly.\n",
    "\nWelcome to PimaCountyHousingSearch.org, a free resource to help you find rentals"
    " in Pima County.\nView listings of apartments, condos, homes for rent, and more."
    " We update our listings daily, so be sure to check back often.\n",
    "\nEmpowering the Black Community by dismantling systemic racism to secure"
    " generational prosperity through advancing; social economic and educational"
    " equity.\n\n",
    "\n",
    "\nWe utilize effective prevention and education strategies with families, teens,"
    " and early educators.\nAt Child & Family Resources, nothing is more important to"
    " us than healthy, happy children. We believe that educated parents and a wealth of"
    " resources are crucial to a child’s success, confidence, and development. Our team"
    " is committed to offering accessible programming that helps parents be the best"
    " they can be and allows children to thrive. We have offices in 13 locations"
    " throughout Arizona.\n",
    "\nAt Sun Tran we pride ourselves on being more than just a bus company. Sun Tran"
    " employees are proud to be a part of Tucson and its close-knit community."
    " Community involvement is one of the factors that distinguishes Sun Tran as an"
    " award-winning transit service, and makes Tucson a better place to call home."
    " Below are a few community programs in which Sun Tran takes part.\n",
    "\nTo end sexual and domestic violence in Arizona by dismantling oppression and"
    " promoting equity among all people. \n\nProviders of direct services to victims"
    " and survivors of sexual and domestic violence are our primary customers. Victims"
    " and survivors are the beneficiaries of our work.\n",
    "\nBeyond the traditional approach of providing survivors with resources including"
    " emergency shelter, safety planning and DV education, Emerge engages the entire"
    " community in addressing the underlying causes of abuse. Why? Domestic abuse is a"
    " community problem, and we believe that our communities are the"
    " solution.\n\nMission\nEmerge provides the opportunity to create, sustain and"
    " celebrate a life free from abuse.\n\nVision\nWe believe that communities where"
    " everyone is safe are possible.\n\nEmerge's Philosophy\nAt Emerge, we believe in"
    " supporting survivors.\n\nWe believe that each survivor’s experience is different,"
    " and therefore, all services are driven by the needs of the survivor and their"
    " family.\nWe believe that a survivor knows their story – and their safety –"
    " best.\nWe address all forms of domestic abuse, not just the physical.\n",
    "\nBeyond the traditional approach of providing survivors with resources including"
    " emergency shelter, safety planning and DV education, Emerge engages the entire"
    " community in addressing the underlying causes of abuse. Why? Domestic abuse is a"
    " community problem, and we believe that our communities are the"
    " solution.\n\nMission\nEmerge provides the opportunity to create, sustain and"
    " celebrate a life free from abuse.\n\nVision\nWe believe that communities where"
    " everyone is safe are possible.\n\nEmerge's Philosophy\nAt Emerge, we believe in"
    " supporting survivors.\n\nWe believe that each survivor’s experience is different,"
    " and therefore, all services are driven by the needs of the survivor and their"
    " family.\nWe believe that a survivor knows their story – and their safety –"
    " best.\nWe address all forms of domestic abuse, not just the physical.\n",
    "\nProvides free individual and group support for older victims of later life"
    " domestic violence, elder abuse, neglect, or financial exploitation. Includes"
    " assistance with orders of protection, court accompaniment, victim compensation,"
    " housing, and other needed services. Also provides advocacy and education.\n",
    "\nThe Victim Services Division supports, educates and empowers people to seek"
    " justice that helps restore them to as nearly whole as possible. Victim Services"
    " advocates assist and provide support to victims at crime scenes, right after an"
    " incident has occurred, and as a victim navigates the criminal justice system."
    " Victims can receive information on community resources, have in-person support at"
    " court hearings and be comforted, emotionally, by an advocate through the Victim"
    " Services Division.\n",
    "\nThe Southern Arizona Center Against Sexual Assault (SACASA) provides crisis"
    " services, advocacy, support, therapy and education for individuals and families"
    " impacted by sexual trauma.  We provide a safe place for survivors to heal, gain"
    " strength, learn coping skills, and develop trusting, caring relationships.\n",
    "\nThe DVLC is an interdisciplinary legal clinic that provides IPV survivors with"
    " pro bono legal services and advice, while connecting clients to needed non-legal"
    " services.\n",
    "\nARC’s skilled professional case managers help seniors escape abusive and"
    " life-threatening situations. We employ the generosity of Tucson area adult care"
    " homeowners to help provide safe temporary housing, acquire immediate medical"
    " care, and transition to long-term housing– all free of charge. Funding is"
    " provided by the US Department of Justice and the Arizona Department of Public"
    " Safety, and Pima County\n\nOur services include:\nProfessional Crisis"
    " Intervention and Support services for people over 50 or for individuals with"
    " disabilities experiencing abuse or neglect\nProfessional Case Management Services"
    " and help navigating the justice system and acquiring appropriate legal and social"
    " services\nObtaining remote orders of protection\nSafety Planning and help"
    " locating accessible long-term housing.\n",
    "\nThe Community Food Bank of Southern Arizona responds to the root causes of"
    " hunger, and seeks to restore dignity, health, opportunity and hope to people"
    " living in poverty. Our mission is to change lives in the communities we serve by"
    " feeding the hungry today, and building a healthy, hunger-free tomorrow.\nOur"
    " programs include emergency food assistance and free meals, as well as a farmers’"
    " market, community gardens, nutrition education, culinary training, support for"
    " local growers and food systems, advocacy, and more.\n",
    "\nProvides a once a month food box to low income individuals and households. The"
    " box is comprised of surplus USDA commodities, donated food items from food"
    " drives, and local resources. We also purchase certain items that we do not get"
    " enough donated, such as peanut butter. We also supplement these boxes with fresh"
    " bread and produce as available. These boxes are meant to provide 2 to 3 days of"
    " assistance while they are seeking additional assistance. We are contracted with"
    " DES to serve Pima, Graham, Greenlee, Cochise, and Santa Cruz Counties.\n\nWe"
    " provide pre-made Food Boxes to 38 partner sites in Pima County who manage the"
    " distribution to clients, and we deliver and handle same day distribution of Food"
    " Boxes to 28 cities throughout Graham, Greenlee, Cochise, and Santa Cruz Counties."
    " Our 4 Branch Banks all provide TEFAP Food Boxes plus they all offer a second"
    " additional Food Box containing non-USDA items such as excess bread, produce, or"
    " store donations.\n",
    "\nThroughout the years, we have held true to our promise to provide healthy,"
    " nutritious meals for people who need them. Every day, Monday through Friday, our"
    " brigade of caring volunteers has delivered lunch and dinner, with love, for"
    " people who are unable to drive, shop, or cook their own meals. Our clients have"
    " always included older persons, people living with disabilities, people facing"
    " tough medical conditions, and people facing end of life issues.\n",
    "\nPima Meals on Wheels is a program of Pima Council on Aging in"
    " collaboration\nwith community subcontracted agencies: Catholic Community Services"
    " and\nLutheran Social Services of the Southwest.\nGood nutrition can help manage,"
    " prevent, or even reverse common health conditions.\nBy getting the proper"
    " nutrition, you can significantly reduce your risk of ongoing health\nissues.\n",
    "\nThe 3000 Club partnered with churches and other non-profit organizations to host"
    " weekly events where semi-truck loads of produce were brought into the valley"
    " where a supporter can donate $10 and receive up to 60 lbs. of produce that they"
    " can share with anyone they know who are in need\n",
    "\nIn 2015, SAAF celebrated 30 years of providing services and continues to be the"
    " only community-based organization in southern Arizona providing case management"
    " and ancillary support services for people living with HIV/AIDS and their"
    " families; culturally appropriate prevention and education programs to reduce the"
    " rate of infection; & LGBTQ community outreach & engagement.\n",
    "\nThe ANCHOR Project (Accessible Network for Coordinated Housing, Opportunities,"
    " and Resilience) is designed to provide culturally responsive and affirming"
    " services to young adults who identify with the spectrum of LGBTQ&A (lesbian, gay,"
    " bisexual, transgender, queer, questioning, and straight ally) communities. As a"
    " team of community partners, the ANCHOR Project is equipped to offer supportive"
    " services in a variety of areas, including:\n\nHousing Stabilization\nSocial"
    " Opportunities\nMental and Emotional Well-being\nCommunity Engagement\nEmployment"
    " Skills\nGoal Achievement\nPersonal Empowerment\nFinancial Education\nRecovery"
    " Support\nEducational Goals\nHealthy Decision-Making\nMuch More!\n",
    "\nWe recognize and respond to the unique concerns of LGBTQI+ older adults who are"
    " 55+ and their younger allies by:\n\nDelivering social and support programming"
    " sponsored by Senior Pride in three areas: Social & Learning, Health & Wellbeing,"
    " and Arts and Culture,\nVetting and sharing LGBTQI+ welcoming information &"
    " services offered by other organizations in the community, and\nIncreasing"
    " awareness of LGBTQI+ and aging issues\n",
    "\nEon Youth Center, a program of Southern Arizona AIDS Foundation, is a safe space"
    " for LGBQIA+ and transgender youth ages 13-23.\n",
    "\nJust as it did at its inception, the Diaper Bank provides diapers to those at or"
    " near the poverty line where no public assistance exists. We recognize that an"
    " inadequate supply of diapers puts families with young children at an increased"
    " risk for health related problems and potential abuse.\n",
    "\nOur services are rooted in compassion and health equity. We offer primary,"
    " specialized, and dental care to all community members. From OB/GYN, midwifery,"
    " and pediatrics to family medicine, physical therapy, and behavioral health, we"
    " tend to the whole patient. Most locations offer pharmacy, radiology, and"
    " laboratory services, as well as health and wellness programs.\n",
    "\nOur services are rooted in compassion and health equity. We offer primary,"
    " specialized, and dental care to all community members. From OB/GYN, midwifery,"
    " and pediatrics to family medicine, physical therapy, and behavioral health, we"
    " tend to the whole patient. Most locations offer pharmacy, radiology, and"
    " laboratory services, as well as health and wellness programs.\n",
    "\nOur services are rooted in compassion and health equity. We offer primary,"
    " specialized, and dental care to all community members. From OB/GYN, midwifery,"
    " and pediatrics to family medicine, physical therapy, and behavioral health, we"
    " tend to the whole patient. Most locations offer pharmacy, radiology, and"
    " laboratory services, as well as health and wellness programs.\n",
    "\nOur services are rooted in compassion and health equity. We offer primary,"
    " specialized, and dental care to all community members. From OB/GYN, midwifery,"
    " and pediatrics to family medicine, physical therapy, and behavioral health, we"
    " tend to the whole patient. Most locations offer pharmacy, radiology, and"
    " laboratory services, as well as health and wellness programs.\n",
    "\nWe believe oral care and dentistry are a vital part of your overall healthcare."
    " We are the largest, non-profit dental program in the state of Arizona, offering a"
    " wide range of general dental care for patients of all ages. Our services include"
    " urgent care, crowns, surgery, dentures, implants and more.\n",
    "\nWe believe oral care and dentistry are a vital part of your overall healthcare."
    " We are the largest, non-profit dental program in the state of Arizona, offering a"
    " wide range of general dental care for patients of all ages. Our services include"
    " urgent care, crowns, surgery, dentures, implants and more.\n",
    "\nOur services are rooted in compassion and health equity. We offer primary,"
    " specialized, and dental care to all community members. From OB/GYN, midwifery,"
    " and pediatrics to family medicine, physical therapy, and behavioral health, we"
    " tend to the whole patient. Most locations offer pharmacy, radiology, and"
    " laboratory services, as well as health and wellness programs.\n",
    "\nOur services are rooted in compassion and health equity. We offer primary,"
    " specialized, and dental care to all community members. From OB/GYN, midwifery,"
    " and pediatrics to family medicine, physical therapy, and behavioral health, we"
    " tend to the whole patient. Most locations offer pharmacy, radiology, and"
    " laboratory services, as well as health and wellness programs.\n",
    "\nOur services are rooted in compassion and health equity. We offer primary,"
    " specialized, and dental care to all community members. From OB/GYN, midwifery,"
    " and pediatrics to family medicine, physical therapy, and behavioral health, we"
    " tend to the whole patient. Most locations offer pharmacy, radiology, and"
    " laboratory services, as well as health and wellness programs.\n",
    "\nWe believe oral care and dentistry are a vital part of your overall healthcare."
    " We are the largest, non-profit dental program in the state of Arizona, offering a"
    " wide range of general dental care for patients of all ages. Our services include"
    " urgent care, crowns, surgery, dentures, implants and more.\n",
    "\nWe attend births at Tucson Medical Center either in Labor & Delivery or at The"
    " Midwifery Center, supporting patients in experiencing childbirth as they wish,"
    " with the pain relief they choose. The Midwifery Center offers an intimate and"
    " supportive environment for natural childbirth with comfortable, homelike birthing"
    " rooms.\n\nOur midwifery care includes: Well-Woman care, waterbirth, childbirth"
    " classes, CenteringPregnancy, BabyLove Group, as well as STD testing and family"
    " planning.\n",
    "\nOur services are rooted in compassion and health equity. We offer primary,"
    " specialized, and dental care to all community members. From OB/GYN, midwifery,"
    " and pediatrics to family medicine, physical therapy, and behavioral health, we"
    " tend to the whole patient. Most locations offer pharmacy, radiology, and"
    " laboratory services, as well as health and wellness programs.\n",
    "\nOur services are rooted in compassion and health equity. We offer primary,"
    " specialized, and dental care to all community members. From OB/GYN, midwifery,"
    " and pediatrics to family medicine, physical therapy, and behavioral health, we"
    " tend to the whole patient. Most locations offer pharmacy, radiology, and"
    " laboratory services, as well as health and wellness programs.\n",
    "\nOur services are rooted in compassion and health equity. We offer primary,"
    " specialized, and dental care to all community members. From OB/GYN, midwifery,"
    " and pediatrics to family medicine, physical therapy, and behavioral health, we"
    " tend to the whole patient. Most locations offer pharmacy, radiology, and"
    " laboratory services, as well as health and wellness programs.\n",
    "\nOur services are rooted in compassion and health equity. We offer primary,"
    " specialized, and dental care to all community members. From OB/GYN, midwifery,"
    " and pediatrics to family medicine, physical therapy, and behavioral health, we"
    " tend to the whole patient. Most locations offer pharmacy, radiology, and"
    " laboratory services, as well as health and wellness programs.\n",
    "\nOur services are rooted in compassion and health equity. We offer primary,"
    " specialized, and dental care to all community members. From OB/GYN, midwifery,"
    " and pediatrics to family medicine, physical therapy, and behavioral health, we"
    " tend to the whole patient. Most locations offer pharmacy, radiology, and"
    " laboratory services, as well as health and wellness programs.\n",
    "\nOBG/YN Services\nComplete Care for Women\nGynecology Care\nObstetrics"
    " Care\nMedication Refills\nEmergency Care\n",
    "\nWe stabilize people during crisis and transition, build a foundation where"
    " people can thrive, and preserve dignity and respect for the most vulnerable. ",
    "\nFor over 49 years, Casa de los Ninos  has served Tucson community to prevent"
    " child abuse and neglect and to support and empower families. We deliver a"
    " continuum of evidence-based services to effectively address the needs of children"
    " and families within our community.\n",
    "\nBirth control methods – Birth Control Pills, Intrauterine Device (IUD), Depo"
    " Provera Shot (DEPO), Implants, Condoms, Ring and Cycle Beads (Natural Family"
    " Planning)\nEmergency contraceptive pills – Emergency contraceptive pills (ECPs),"
    " also known as the morning after pill, are available at our offices. If taken"
    " within 72 – 120 hours of unprotected sex (a condom breaks, pills are forgotten),"
    " they can greatly reduce the risk of pregnancy.\nPregnancy testing and"
    " counseling\nBreast exams – If abnormalities are detected, referrals are given to"
    " the Well Woman HealthCheck program.\nExaminations – Pelvic and/or pap tests as"
    " needed.\nAbnormal Pap smear treatment – If the results of your Pap Smear are"
    " abnormal, we will refer you to their Colposcopy Clinic or suggest a treatment"
    " plan according to your needs.\nSTI Screening and Treatment - Remember, many STIs"
    " have no symptoms.\nCounseling and education - We want to give you all the"
    " information you need to make educated and healthy choices in planning a"
    " family.\nThe Pima County Health Department offers immunizations for children and"
    " adults\n",
    "\nBirth control methods – Birth Control Pills, Intrauterine Device (IUD), Depo"
    " Provera Shot (DEPO), Implants, Condoms, Ring and Cycle Beads (Natural Family"
    " Planning)\nEmergency contraceptive pills – Emergency contraceptive pills (ECPs),"
    " also known as the morning after pill, are available at our offices. If taken"
    " within 72 – 120 hours of unprotected sex (a condom breaks, pills are forgotten),"
    " they can greatly reduce the risk of pregnancy.\nPregnancy testing and"
    " counseling\nBreast exams – If abnormalities are detected, referrals are given to"
    " the Well Woman HealthCheck program.\nExaminations – Pelvic and/or pap tests as"
    " needed.\nAbnormal Pap smear treatment – If the results of your Pap Smear are"
    " abnormal, we will refer you to their Colposcopy Clinic or suggest a treatment"
    " plan according to your needs.\nSTI Screening and Treatment - Remember, many STIs"
    " have no symptoms.\nCounseling and education - We want to give you all the"
    " information you need to make educated and healthy choices in planning a"
    " family.\nThe Pima County Health Department offers immunizations for children and"
    " adults\n",
    "\nBirth control methods – Birth Control Pills, Intrauterine Device (IUD), Depo"
    " Provera Shot (DEPO), Implants, Condoms, Ring and Cycle Beads (Natural Family"
    " Planning)\nEmergency contraceptive pills – Emergency contraceptive pills (ECPs),"
    " also known as the morning after pill, are available at our offices. If taken"
    " within 72 – 120 hours of unprotected sex (a condom breaks, pills are forgotten),"
    " they can greatly reduce the risk of pregnancy.\nPregnancy testing and"
    " counseling\nBreast exams – If abnormalities are detected, referrals are given to"
    " the Well Woman HealthCheck program.\nExaminations – Pelvic and/or pap tests as"
    " needed.\nAbnormal Pap smear treatment – If the results of your Pap Smear are"
    " abnormal, we will refer you to their Colposcopy Clinic or suggest a treatment"
    " plan according to your needs.\nSTI Screening and Treatment - Remember, many STIs"
    " have no symptoms.\nCounseling and education - We want to give you all the"
    " information you need to make educated and healthy choices in planning a"
    " family.\nThe Pima County Health Department offers immunizations for children and"
    " adults\n",
    "\nBirth control methods – Birth Control Pills, Intrauterine Device (IUD), Depo"
    " Provera Shot (DEPO), Implants, Condoms, Ring and Cycle Beads (Natural Family"
    " Planning)\nEmergency contraceptive pills – Emergency contraceptive pills (ECPs),"
    " also known as the morning after pill, are available at our offices. If taken"
    " within 72 – 120 hours of unprotected sex (a condom breaks, pills are forgotten),"
    " they can greatly reduce the risk of pregnancy.\nPregnancy testing and"
    " counseling\nBreast exams – If abnormalities are detected, referrals are given to"
    " the Well Woman HealthCheck program.\nExaminations – Pelvic and/or pap tests as"
    " needed.\nAbnormal Pap smear treatment – If the results of your Pap Smear are"
    " abnormal, we will refer you to their Colposcopy Clinic or suggest a treatment"
    " plan according to your needs.\nSTI Screening and Treatment - Remember, many STIs"
    " have no symptoms.\nCounseling and education - We want to give you all the"
    " information you need to make educated and healthy choices in planning a"
    " family.\nThe Pima County Health Department offers immunizations for children and"
    " adults\n",
    "\nPlanned Parenthood is one of the nation’s leading providers of high-quality,"
    " affordable health care, and the nation’s largest provider of sex education. With"
    " or without insurance, you can always come to us for your health care.\nYou can"
    " come to us for services that don’t require a medical exam. For example, birth"
    " control education and supplies; emergency contraception (AKA the morning after"
    " pill); pregnancy testing and counseling; STD testing, and testing and treatments"
    " for urinary tract infections.\n",
    "\nThrough education and support, we—as individuals and faith communities—work to"
    " build bridges, reduce stigma and sustain hope. We invite the community to join us"
    " in an informed, sensitive and compassionate response to those affected by"
    " HIV/AIDS. \nEDUCATION\nWe provide HIV awareness, education, and prevention"
    " programs to help address the stigma and to build knowledge, understanding, and"
    " support.\n\nSUPPORT\nWe offer numerous and unique support services for people"
    " living with HIV, providing classes, resources, and services to help people with"
    " HIV to live well.\n\nWORK WITH INTERFAITH COMMUNITIES\nWe engage faith"
    " communities to learn and serve the needs of the HIV community in Southern"
    " Arizona.\n\nPROVIDING RESOURCES\nWe are committed to finding and creating"
    " resources for education, awareness, and community engagement.\n",
    "\nFoster Family Care\nImmigration\nChildcare and Early Childhood Education\nCase"
    " Management for Seniors and Persons with Disabilities in Gila County\nCounseling -"
    " CCS - Tucson\nImmigrant Survivors Legal Assistance\nMigration and Refugee"
    " Services\nSenior Nutrition – Congregate Meals - CCS - Tucson\nSenior Nutrition –"
    " Home-Delivered Meals - CCS - Tucson\nBasic Services: Food, Clothing and"
    " Housewares\nHousing Counseling\nJohn Valenzuela Youth Center\nFinancial Education"
    " and Asset Building\nSenior Housing for low-income elders\nTax"
    " Services\nTransitional Housing\nFamily Preservation Services (In-Home"
    " Services)\nFamily Preservation Services (Parent Aide & Supervised Visits) -"
    " CCS-Sierra Vista\nDomestic Violence Programs\nSenior Nutrition – Congregate Meals"
    " - CCS-Sierra Vista\nSenior Nutrition – Home-Delivered Meals - CCS-Sierra"
    " Vista\nArizona/New Mexico Interpreting SuperCenter\nCommunity Living"
    " Program\nCommunity Outreach Program for the Deaf\nCommunity Outreach Program for"
    " the Deaf - New Mexico\nValley Center of the Deaf\nCounseling - CCS-Yuma\nDaybreak"
    " Adult Day Health Care\nSafe House – Domestic Violence Shelter\nSenior Nutrition –"
    " Home-Delivered Meals - CCS-Yuma\nSenior Nutrition – Congregate Meals -"
    " CCS-Yuma\nCasa Alitas Program - Aid for Migrant Families\nKolbe Society\nSt."
    " Jeanne Jugan Ministry with Elders\niCanConnect\nAdoption (Certified) CCS -"
    " Tucson\nAdvance Care Planning\nSacraments for the Elderly\nSign-up for"
    " Flocknote\nAdopción- CCS Sierra Vista\nAdoption CCS - Sierra Vista\nCUIDADO DE"
    " CRIANZA TEMPORAL\nFoster Care\n",
    "\nFoster Family Care\nImmigration\nChildcare and Early Childhood Education\nCase"
    " Management for Seniors and Persons with Disabilities in Gila County\nCounseling -"
    " CCS - Tucson\nImmigrant Survivors Legal Assistance\nMigration and Refugee"
    " Services\nSenior Nutrition – Congregate Meals - CCS - Tucson\nSenior Nutrition –"
    " Home-Delivered Meals - CCS - Tucson\nBasic Services: Food, Clothing and"
    " Housewares\nHousing Counseling\nJohn Valenzuela Youth Center\nFinancial Education"
    " and Asset Building\nSenior Housing for low-income elders\nTax"
    " Services\nTransitional Housing\nFamily Preservation Services (In-Home"
    " Services)\nFamily Preservation Services (Parent Aide & Supervised Visits) -"
    " CCS-Sierra Vista\nDomestic Violence Programs\nSenior Nutrition – Congregate Meals"
    " - CCS-Sierra Vista\nSenior Nutrition – Home-Delivered Meals - CCS-Sierra"
    " Vista\nArizona/New Mexico Interpreting SuperCenter\nCommunity Living"
    " Program\nCommunity Outreach Program for the Deaf\nCommunity Outreach Program for"
    " the Deaf - New Mexico\nValley Center of the Deaf\nCounseling - CCS-Yuma\nDaybreak"
    " Adult Day Health Care\nSafe House – Domestic Violence Shelter\nSenior Nutrition –"
    " Home-Delivered Meals - CCS-Yuma\nSenior Nutrition – Congregate Meals -"
    " CCS-Yuma\nCasa Alitas Program - Aid for Migrant Families\nKolbe Society\nSt."
    " Jeanne Jugan Ministry with Elders\niCanConnect\nAdoption (Certified) CCS -"
    " Tucson\nAdvance Care Planning\nSacraments for the Elderly\nSign-up for"
    " Flocknote\nAdopción- CCS Sierra Vista\nAdoption CCS - Sierra Vista\nCUIDADO DE"
    " CRIANZA TEMPORAL\nFoster Care\n",
    "\nDerechos Humanos is a grassroots organization that promotes the human and civil"
    " rights of all migrants regardless of their immigration status. Consequently, we"
    " fight the militarization of our southern border home and combat the"
    " discrimination and human rights abuses of both our citizen and non-citizen"
    " brothers and sisters.\n\nIn the context of an increasingly militarized border and"
    " the criminalization of immigration, Derechos Humanos works to empower those most"
    " directly impacted to create change and promote justice, challenging the borders"
    " that seek to divide us.\n\nOur goals include:\n\nStrengthening the capacity of"
    " the border & urban communities to exercise their rights and participate in public"
    " policy decisions\nIncreasing public awareness of the magnitude of human rights"
    " abuses, deaths and assaults at the border resulting from U.S. policy\nSeeking"
    " changes in government policies that result in human suffering because of the"
    " militarization of the U.S. border region\n",
    "\nThe Florence Immigrant & Refugee Rights Project provides free legal and social"
    " services to detained adults and children under threat of deportation.\n",
    "\nIskashitaa Refugee Network creates opportunities to integrate UN refugees into"
    " the Southern Arizona community while educating the public and strengthening the"
    " local food system, reducing local food waste, and increasing food security. \n",
    "\nPrevents seniors and individuals with disabilities from experiencing isolation,"
    " loneliness, and health risks, so that they can live safely in their homes and"
    " within their communities. Includes home care, habilitation, meals on wheels, and"
    " grocery shopping services. \nChildren and Family Services builds strong families"
    " to help children grow in safe and loving families through a comprehensive range"
    " of services, which you can explore by clicking below!\nToday, LSS-SW Emergency"
    " Services, in partnership with faith partners and hardworking volunteers, relieves"
    " hunger and homelessness for neighbors facing extreme poverty through food"
    " pantries, rent & utility assistance,  emergency shelter, and disaster"
    " preparedness. \nOur services include:\n\nPre-arrival housing\n\nCase"
    " management\n\nNavigating transportation and basic public services\n\nEmployment"
    " support\n\nK-12 refugee education services\n\nWomen's empowerment\n\nImmigration"
    " services\n\nTucson Refugee Youth Mentor Program\nAsylum-seekers are legally"
    " entering the United States for fear of persecution in their home country. LSS-SW"
    " works with partners, including local churches and community organizations, to"
    " provide humanitarian assistance including food, clothing and hygiene products,"
    " case management and coordination, travel assistance, and legal"
    " orientation.\n\nYou have been wondering if your dreams could come true one day"
    " because you didn’t get an opportunity to finish your studies. Lutheran Social"
    " services of the Southwest Family Resource Centers are here to help you achieving"
    " your goals. You can pave your path to success by earning a GED credential, taking"
    " ESL classes and learning more about managing your finances.  \n",
    "\nMerciful is a nonprofit organization in Tucson, Arizona that advocate on behalf"
    " of refugees and immigrants for access to professional and educational resources"
    " so that families can make a successful cultural, economic, and social transition"
    " to life in the United States, and, to provide services to assist families in"
    " becoming economically stable, civically engaged members of our new community of"
    " Tucson, Arizona\n",
    "\nThe RefAid mobile app shows migrants, refugees and those who help them where"
    " services are near them – on a map with a very simple interface. A web based"
    " content management and communication system allows trusted aid organizations to"
    " manage and update their services and to get their critical aid to where it is"
    " most urgently needed.\n",
    "\nThe Immigration Law Clinic provides legal representation mostly to non-detained"
    " immigrants in Tucson, Arizona and to some immigrants detained in Eloy, Arizona,"
    " in their deportation cases. \u200bOur clients have included asylum seekers,"
    " victims of domestic violence, and long-time permanent residents seeking"
    " humanitarian waivers of removal. We have represented immigrants from countries"
    " including Afghanistan, Mexico, Ethiopia, Vietnam, and Nepal. \n",
    "\nThe Workers' Rights Clinic at the University of Arizona James E. Rogers College"
    " of Law is dedicated to training the next generation of lawyers through close"
    " supervision and hands-on experience in direct client representation, community"
    " education and outreach, and policy research and writing.\n\nOur work focuses on"
    " the intersection of immigration, employment and labor laws to support the rights"
    " of low-wage workers from immigrant communities throughout Arizona. We are the"
    " only clinic in the state that provides free legal services to low-wage workers"
    " and that operates a Worker Hotline. Our students begin with the desire to serve"
    " underrepresented communities and leave armed with the knowledge and on-the-ground"
    " experience necessary to excel in any legal career path they choose. \n",
    "\nThe Arizona Center for Disability Law (ACDL) is a not for profit public interest"
    " law firm, dedicated to protecting the rights of individuals with physical,"
    " mental, psychiatric, sensory and cognitive disabilities.\n\n\nWho We Help\nWe"
    " provide a variety of legal services to people with disabilities and/or"
    " disability-related problems. We focus primarily on those cases in which"
    " individuals have nowhere else to go for legal support.\n\n\nWhat We Do\nWe"
    " provide information, outreach and training on legal rights and self-advocacy,"
    " represent individuals in negotiations, administrative proceedings and court, and"
    " investigate abuse and neglect.\n",
    "\nAlternative Dispute Resolution\nConsumer Issues / Bankruptcy\nContributing"
    " Attorney\nCourt Information\nCriminal Law\nDisaster Relief\nFamily and"
    " Children\nHealth & Disability\nHousing\nIdentity"
    " Theft\nImmigration\nInsurance\nLife & Estate Planning\nNative American"
    " Issues\nProtection from Abuse\nPublic Benefits\nPublic Utilities &"
    " Energy\nSeniors\nTax\nVeterans\nWork\nYour Rights\n",
    "\nAsylum seekers request safe haven in the United States and other countries"
    " because they fear persecution in their homeland. Asylum seekers are not the same"
    " as refugees. Asylum seekers first obtain admittance to the U.S., and then apply"
    " for protection. Refugees apply for protection while still outside of the United"
    " States.\n\nImmigrants who are in the U.S. may request asylum if they have been"
    " persecuted or have a well-founded fear of persecution in their country of origin"
    " due to race, religion, nationality, membership in a particular social group or"
    " political opinion. An asylum seeker has only one year to apply for asylum after"
    " entering the U.S..\n",
    "\nWe provide a variety of employment-related programs, as well as the education"
    " and socialization necessary for our clients to lead meaningful, productive lives."
    " Beacon Group enterprises offer local businesses high-quality sub-contract"
    " services such as custodial and landscaping, contract manufacturing and packaging,"
    " cable assembly, fleet and facility services, paint recycling and confidential"
    " document shredding, among others.\n",
    "\nH.E.L.P. provides free and reduced fee legal care to those with a terminal"
    " illness. We understand legal issues can directly impact health and quality of"
    " life for everyone involved with a terminal illness. We provide legal care to"
    " those who normally may not have access to legal care.\n",
    "\nThe KARE Family Center provides specialized case management and other services"
    " to relatives and non-relatives caring for youth, as well as clinical case"
    " management for youth and families who need help attaining or maintaining"
    " permanency, and for young adults transitioning from foster care.\n",
    "\nOur mission is to provide service and leadership to the public and to the"
    " profession, to provide to all people of Pima County access to and awareness of"
    " the law, and to promote respect for and satisfaction in the profession.  \n",
    "\nWe provide civil legal aid. We do not provide help with criminal legal issues."
    " Examples of civil legal issues include: eviction, foreclosure, public benefits"
    " denial, guardianship of children in your care, Orders of Protection (restraining"
    " order) for victims of domestic violence, divorce and child support issues. Our"
    " ability to help depends on the availability of funding and other resources. We"
    " are committed to helping as many people as we can, so we encourage you to apply."
    " If we cannot help you directly for any reason, we will suggest other resources in"
    " your area.\n",
    "\nStep Up to Justice is a full-service free civil legal center for low-income"
    " individuals and families in Pima County, powered by the talents of volunteer"
    " attorneys and the efficient use of technology and funding. A public service by"
    " private citizens, Step Up to Justice harnesses the energy of volunteer attorneys"
    " and channels that resource to members of the community who need but cannot afford"
    " legal services.  Step Up to Justice relies on innovation in technology to bring"
    " civil legal services to clients where and when they need them. By targeting funds"
    " at the infrastructure necessary to connect clients in need with volunteers ready"
    " to help, Step Up to Justice reaches clients, recruits volunteers, builds"
    " partnerships, and provides free civil legal services efficiently and at a low"
    " cost.\n",
    "\nThe Child and Family Law Clinic is a working law office in which law students,"
    " working in multi-disciplinary teams, represent children in child protection"
    " proceedings and adult victims of domestic violence.\n\nWe are committed to"
    " providing a quality, supervised, multi-disciplinary learning environment for law"
    " students and masters of social work interns. The clinic is dedicated to"
    " representing, with integrity, the interests of children and adult victims"
    " involved with the justice system. Students seek to empower clients by encouraging"
    " their active participation, when safe, at every stage of the legal process.\n",
    "\nEasterseals is leading the way to full equity, inclusion, and access by"
    " enriching education, enhancing health, expanding employment, and elevating"
    " community.\n\nWe do this through life-changing services and on-the-ground"
    " supports for children and adults with disabilities, families, and local"
    " communities across the country.\n\nHelpful Topics\nAutism\nEmployment & Job"
    " Training\nMental Health Services\nTherapy & Rehabilitative"
    " Care\nTransportation\nShow Me Services For\nChildren & Families\nEarly"
    " Intervention\nChild Development Screening Tool\nInclusive Child Care\nEarly"
    " Childhood Education\nCamp & Recreation\nFamily Support &"
    " Resources\nAdults\nEmployment & Job Training\nYouth & Transition\nIn-Home"
    " Care\nAdult Day Services\nCamp & Recreation\nTransportation\nSeniors\nEmployment"
    " for Seniors\nIn-Home Care\nAdult Day Services\nTherapy & Rehabilitative"
    " Care\nTransportation\nVeterans\nResources For Veterans\nMilitary & Veteran"
    " Caregivers\nCaregivers\nCaregiving Services\nRespite Services\n",
    "\nThe COPE Line is a resource for grieving individuals with a need for support."
    " Our COPE Line Volunteers are trained to respond to each caller personally by"
    " providing resources, referrals and information or simply offering emotional"
    " support.\n",
    "\nWe serve\npeople whose lives have been upended by war, conflict and natural"
    " disasters\nWe work\nin countries where people don’t have the support they need to"
    " recover from crisis\nWe respond\nwithin 72 hours, staying to help countries"
    " stabilize and people rebuild their lives\nWe resettle\nrefugees welcomed by the"
    " United States, helping them to succeed and thrive\n",
    "\nNational Suicide Prevention Lifeline\n",
    "\nNational Suicide Prevention Lifeline\n",
    "\nThere are many factors that can lead to substance misuse, such as past abuse and"
    " trauma, stressful life experiences, sadness and being around others who are"
    " using.\n\nSometimes, an undiagnosed illness can lead to drug use to help with"
    " pain or other symptoms.\n\nOur team will help you figure out what level of"
    " support, treatment and services will be best for you. And, we will help you work"
    " to meet your recovery goals.\n",
    "\nCODAC believes there are many ways to feel better, and offers you holistic"
    " wellness services to complement your behavioral health and primary care"
    " services.\n\nOur Wellness services can help you with pain management,"
    " self-confidence, physical wellbeing and sleep.\n",
    "\nCODAC believes there are many ways to feel better, and offers you holistic"
    " wellness services to complement your behavioral health and primary care"
    " services.\n\nOur Wellness services can help you with pain management,"
    " self-confidence, physical wellbeing and sleep.\n",
    "\nCODAC believes there are many ways to feel better, and offers you holistic"
    " wellness services to complement your behavioral health and primary care"
    " services.\n\nOur Wellness services can help you with pain management,"
    " self-confidence, physical wellbeing and sleep.\n",
    "\nAs one of the first licensed integrated care clinics in Arizona, Community"
    " Partners Integrated Healthcare has grown from 1 clinic with 40 members in 2014 to"
    " multiple locations in 8 counties, serving close to 11,000 members today. And we"
    " continue to evolve. We are a leading integrated care organization in Arizona with"
    " a strong presence in Phoenix, Tucson and the rural communities that comprise a"
    " majority of Central and Southern Arizona.\nHousing Assistance\n\nCommunity"
    " Partners Housing Assistance believes in promoting easy access to housing support,"
    " and helping those with serious mental illness or substance use disorder build a"
    " foundation for long-term housing stability and greater wellness. As the"
    " Collaborative Applicant for the U.S. Housing and Urban Development (HUD)"
    " Continuum of Care (CoC) Program in Pima County, we are committed to the CoC and"
    " the community by providing direct housing placement for individuals.\n",
    "\nAs one of the first licensed integrated care clinics in Arizona, Community"
    " Partners Integrated Healthcare has grown from 1 clinic with 40 members in 2014 to"
    " multiple locations in 8 counties, serving close to 11,000 members today. And we"
    " continue to evolve. We are a leading integrated care organization in Arizona with"
    " a strong presence in Phoenix, Tucson and the rural communities that comprise a"
    " majority of Central and Southern Arizona.\nHousing Assistance\n\nCommunity"
    " Partners Housing Assistance believes in promoting easy access to housing support,"
    " and helping those with serious mental illness or substance use disorder build a"
    " foundation for long-term housing stability and greater wellness. As the"
    " Collaborative Applicant for the U.S. Housing and Urban Development (HUD)"
    " Continuum of Care (CoC) Program in Pima County, we are committed to the CoC and"
    " the community by providing direct housing placement for individuals.\n",
    "\nMedical Services\nProviding Medical care for overall wellness.\n\nBehavioral"
    " Health Services\nWe help our members in their treatment and recovery.\n\nTherapy"
    " Services\nDevelop skills and gain insight to improve the quality of your"
    " life.\n\nYouth Services\nStrengthening youth and families.\n\nCommunity Health"
    " Services\nEducating and Promoting healthier lifestyles.\n\nCOPE provides best"
    " practice-based, integrated physical and mental healthcare to improve the health"
    " and well-being of each person and community we serve.\n",
    "\nMedical Services\nProviding Medical care for overall wellness.\n\nBehavioral"
    " Health Services\nWe help our members in their treatment and recovery.\n\nTherapy"
    " Services\nDevelop skills and gain insight to improve the quality of your"
    " life.\n\nYouth Services\nStrengthening youth and families.\n\nCommunity Health"
    " Services\nEducating and Promoting healthier lifestyles.\n\nCOPE provides best"
    " practice-based, integrated physical and mental healthcare to improve the health"
    " and well-being of each person and community we serve.\n",
    "\nMedical Services\nProviding Medical care for overall wellness.\n\nBehavioral"
    " Health Services\nWe help our members in their treatment and recovery.\n\nTherapy"
    " Services\nDevelop skills and gain insight to improve the quality of your"
    " life.\n\nYouth Services\nStrengthening youth and families.\n\nCommunity Health"
    " Services\nEducating and Promoting healthier lifestyles.\n\nCOPE provides best"
    " practice-based, integrated physical and mental healthcare to improve the health"
    " and well-being of each person and community we serve.\n",
    "\nMedical Services\nProviding Medical care for overall wellness.\n\nBehavioral"
    " Health Services\nWe help our members in their treatment and recovery.\n\nTherapy"
    " Services\nDevelop skills and gain insight to improve the quality of your"
    " life.\n\nYouth Services\nStrengthening youth and families.\n\nCommunity Health"
    " Services\nEducating and Promoting healthier lifestyles.\n\nCOPE provides best"
    " practice-based, integrated physical and mental healthcare to improve the health"
    " and well-being of each person and community we serve.\n",
    "\nMedical Services\nProviding Medical care for overall wellness.\n\nBehavioral"
    " Health Services\nWe help our members in their treatment and recovery.\n\nTherapy"
    " Services\nDevelop skills and gain insight to improve the quality of your"
    " life.\n\nYouth Services\nStrengthening youth and families.\n\nCommunity Health"
    " Services\nEducating and Promoting healthier lifestyles.\n\nCOPE provides best"
    " practice-based, integrated physical and mental healthcare to improve the health"
    " and well-being of each person and community we serve.\n",
    "\nBehavioral Health Services\nWe help our members in their treatment and"
    " recovery.\n\nCOPE provides best practice-based, integrated physical and mental"
    " healthcare to improve the health and well-being of each person and community we"
    " serve.\n",
    "\nMedical Services\nProviding Medical care for overall wellness.\n\nBehavioral"
    " Health Services\nWe help our members in their treatment and recovery.\n\nTherapy"
    " Services\nDevelop skills and gain insight to improve the quality of your"
    " life.\n\nYouth Services\nStrengthening youth and families.\n\nCommunity Health"
    " Services\nEducating and Promoting healthier lifestyles.\n\nCOPE provides best"
    " practice-based, integrated physical and mental healthcare to improve the health"
    " and well-being of each person and community we serve.\n",
    "\nMedical Services\nProviding Medical care for overall wellness.\n\nBehavioral"
    " Health Services\nWe help our members in their treatment and recovery.\n\nTherapy"
    " Services\nDevelop skills and gain insight to improve the quality of your"
    " life.\n\nYouth Services\nStrengthening youth and families.\n\nCommunity Health"
    " Services\nEducating and Promoting healthier lifestyles.\n\nCOPE provides best"
    " practice-based, integrated physical and mental healthcare to improve the health"
    " and well-being of each person and community we serve.\n",
    "\nLa Frontera Center provides outpatient and residential mental health and"
    " substance abuse treatment services to children, youth, and adults in Pima County,"
    " Arizona.\n",
    "\nLa Frontera Center provides outpatient and residential mental health and"
    " substance abuse treatment services to children, youth, and adults in Pima County,"
    " Arizona.\n",
    "\nLa Frontera Center provides outpatient and residential mental health and"
    " substance abuse treatment services to children, youth, and adults in Pima County,"
    " Arizona.\n",
    "\nLa Frontera Center provides outpatient and residential mental health and"
    " substance abuse treatment services to children, youth, and adults in Pima County,"
    " Arizona.\n",
    "\nLa Frontera Center provides outpatient and residential mental health and"
    " substance abuse treatment services to children, youth, and adults in Pima County,"
    " Arizona.\n",
    "\nLa Frontera Center provides outpatient and residential mental health and"
    " substance abuse treatment services to children, youth, and adults in Pima County,"
    " Arizona.\n",
    "\nLa Frontera Center provides outpatient and residential mental health and"
    " substance abuse treatment services to children, youth, and adults in Pima County,"
    " Arizona.\n",
    "\nLa Frontera Center provides outpatient and residential mental health and"
    " substance abuse treatment services to children, youth, and adults in Pima County,"
    " Arizona.\n",
    "\nLa Frontera Center provides outpatient and residential mental health and"
    " substance abuse treatment services to children, youth, and adults in Pima County,"
    " Arizona.\n",
    "\nLa Frontera Center provides outpatient and residential mental health and"
    " substance abuse treatment services to children, youth, and adults in Pima County,"
    " Arizona.\n",
    "\nThe CoppeRX Card gives Medicare-eligible residents a simple way to get"
    " substantial discounts on spiraling prescription drug prices. The CoppeRX Card"
    " is:\n\nFree of charge - Anyone 65 or older or disabled is entitled to a free"
    " CoppeRX Card. Just call (888) 227-8315.\nFree of restrictions - It applies to all"
    " prescription drug purchases.\nFree of hassles - Just present it to any one of 500"
    " pharmacies throughout Arizona to receive a discount on your prescription"
    " purchase. Generally, CoppeRX Card discounts range from 15 to 55 percent.\nFree of"
    " expiration dates - This benefit does not expire in 2009. It will continue to"
    " offer discounts after the Medicare cards expire.\n",
    "\nMaking sure you get the medication you need is our priority. You can decide the"
    " most convenient way to fill your Rx – with options like contactless delivery to"
    " your door or pickup at a pharmacy in your network. The choice is yours.\n",
    "\nThe Walmart $4 Prescriptions program requires no membership, no fee, and no"
    " insurance, and offers patients discounted medications in 30-day and 90-day"
    " supplies. Often referred to as “Walmart’s $4 generic list,” the program includes"
    " nearly 100 different generic medications from between $4 and $40.\n",
    "\nPhRMA’s Medicine Assistance Tool (MAT) is a search engine designed to help"
    " patients, caregivers and health care providers learn more about the resources"
    " available through the various biopharmaceutical industry programs. MAT is not its"
    " own patient assistance program, but rather a search engine for many of the"
    " patient assistance resources that the biopharmaceutical industry offers.\n",
    "\nOur faith-based recovery program helps struggling men and women uncover and"
    " address the spiritual, physical, emotional, and mental barriers that kept them"
    " lost in addiction. Being part of a community is vital for recovery, but we also"
    " feel that each person’s journey is unique and should be respected as such. Our"
    " guests meet both in groups and in one-on-one sessions with a recovery coach as we"
    " come alongside each individual and walk this journey with them, letting them know"
    " they are not alone. Our goal is for our guests to find a new beginning with"
    " lasting restoration and peace so they can lead fulfilling, productive, and"
    " self-sufficient lives.\n",
    "\n\nOur ministry is based on healthy relationships, teaching, and grace.\n\nWhen"
    " guests arrive, they are welcomed and offered a nutritious meal. Our team of"
    " compassionate advocates works with guests to assess their needs and develop a"
    " plan that helps them establish stability and reclaim their lives.\n\nMost guests"
    " come to us with several obstacles that need to be addressed for them to be"
    " successful. These might be unemployment, lack of education, mental health issues,"
    " trauma, abuse, and addiction. Learn about our Recovery Program.\n",
    "\nWe welcome the hungry and hurting; we address their immediate needs; we build"
    " authentic relationships; and we share the Gospel so that total transformation"
    " happens. The grace of Christ is an amazing gift to be shared with everyone. We"
    " dedicate our lives to the homeless and the poor, and we know that God provides"
    " complete life change to those who place their trust in Him. Our holistic approach"
    " addresses the needs of the whole person—mind, body, and spirit. We work in"
    " collaboration with those who are passionate about bringing permanent solutions to"
    " the crisis of homelessness.\n",
    "\nThe Primavera Foundation provides pathways out of poverty through safe,"
    " affordable housing, workforce development, and neighborhood"
    " revitalization.\n\nVISION\nTo promote social and economic justice, while working"
    " to build a future in which all people are assured basic human rights, a livable"
    " income, and safe, affordable housing.\n\nVALUES\nWe believe in the intrinsic"
    " value of every individual, and that everyone deserves a voice and has the ability"
    " to make a difference.\n\nGOALS\n\nEconomic empowerment and long-term financial"
    " security\nNeighborhood revitalization\nCommunity and civic engagement\nEmpowering"
    " the most marginalized in our community to affect long-term positive change for"
    " themselves and their families\n",
    "\nThe Primavera Foundation provides pathways out of poverty through safe,"
    " affordable housing, workforce development, and neighborhood"
    " revitalization.\n\nVISION\nTo promote social and economic justice, while working"
    " to build a future in which all people are assured basic human rights, a livable"
    " income, and safe, affordable housing.\n\nVALUES\nWe believe in the intrinsic"
    " value of every individual, and that everyone deserves a voice and has the ability"
    " to make a difference.\n\nGOALS\n\nEconomic empowerment and long-term financial"
    " security\nNeighborhood revitalization\nCommunity and civic engagement\nEmpowering"
    " the most marginalized in our community to affect long-term positive change for"
    " themselves and their families\n",
    "\nThe Primavera Foundation provides pathways out of poverty through safe,"
    " affordable housing, workforce development, and neighborhood"
    " revitalization.\n\nVISION\nTo promote social and economic justice, while working"
    " to build a future in which all people are assured basic human rights, a livable"
    " income, and safe, affordable housing.\n\nVALUES\nWe believe in the intrinsic"
    " value of every individual, and that everyone deserves a voice and has the ability"
    " to make a difference.\n\nGOALS\n\nEconomic empowerment and long-term financial"
    " security\nNeighborhood revitalization\nCommunity and civic engagement\nEmpowering"
    " the most marginalized in our community to affect long-term positive change for"
    " themselves and their families\n",
    "Primavera's Project Action for Veterans program provides housing support services"
    " and temporary financial assistance to veterans and their families that are facing"
    " eviction or homelessness. Services are aimed at addressing barriers that threaten"
    " the veteran and/or their family’s housing stability. The program acts as a"
    " resource liaison connecting veterans to public and community resources that are"
    " vital to a better quality of life.\n\nSupport services include but are not"
    " limited to connecting veterans with the following resources:\n\nVA benefits\njob"
    " training assistance\nhealthcare services\ndaily living services\npersonal"
    " financial planning services\nincome support services (TANF, disability benefits,"
    " etc.)\nfiduciary and representative payee services\nlegal services\nchildcare"
    " services\nTemporary financial assistance is provided for the following:\n\nrent"
    " and utilities deposits\ntransportation\nmoving\n",
    "\nThe Primavera Foundation provides pathways out of poverty through safe,"
    " affordable housing, workforce development, and neighborhood"
    " revitalization.\n\nVISION\nTo promote social and economic justice, while working"
    " to build a future in which all people are assured basic human rights, a livable"
    " income, and safe, affordable housing.\n\nVALUES\nWe believe in the intrinsic"
    " value of every individual, and that everyone deserves a voice and has the ability"
    " to make a difference.\n\nGOALS\n\nEconomic empowerment and long-term financial"
    " security\nNeighborhood revitalization\nCommunity and civic engagement\nEmpowering"
    " the most marginalized in our community to affect long-term positive change for"
    " themselves and their families\n",
    "\nHomeless Families\nWhen a family is experiencing homelessness, Our Family"
    " Services is a point of entry for them to launch their fresh start.\n\nHomeless"
    " Youth\nWhen a young person engages with Our Family staff, they receive"
    " comprehensive services that meet their unique needs.\n\nReunion House\nWe are"
    " proud of our Reunion House shelter—a crisis shelter for abused, homeless, and"
    " runaway teens (ages 12 – 17); it’s the only shelter of its kind in all of"
    " Southern Arizona.\n",
    "\nThe Salvation Army Tucson is helping families in need with our food pantry. You"
    " can help make sure one less person goes to bed hungry by donating canned, boxed"
    " and bagged food items to one of our food pantries\n",
    "\nAlcoholics Anonymous is a fellowship of people who come together to solve their"
    " drinking problem.  It doesn’t cost anything to attend A.A. meetings. There are no"
    " age or education requirements to participate. Membership is open to anyone who"
    " wants to do something about their drinking problem.\n\nA.A.’s primary purpose is"
    " to help alcoholics to achieve sobriety.\n",
    "\nThe Al-Anon Family Groups are a fellowship of relatives and friends of"
    " alcoholics who share their experience, strength, and hope in order to solve their"
    " common problems. We believe alcoholism is a family illness and that changed"
    " attitudes can aid recovery.\n\nAl-Anon is not allied with any sect, denomination,"
    " political entity, organization, or institution; does not engage in any"
    " controversy; neither endorses nor opposes any cause. There are no dues for"
    " membership. Al-Anon is self-supporting through its own voluntary"
    " contributions.\n\nAl-Anon has but one purpose: to help families of alcoholics. We"
    " do this by practicing the Twelve Steps, by welcoming and giving comfort to"
    " families of alcoholics, and by giving understanding and encouragement to the"
    " alcoholic.\n",
    "\nThe ASHLine provides individualized coaching and offers up to four weeks free of"
    " nicotine replacement therapy such as patches, lozenges, and gum.\n",
    "\nThe one promise of NA is that an addict, any addict, can stop using drugs, lose"
    " the desire to use, and learn a new way of life.\n",
    "\nOne of the leading human and social service organizations in Pima County is the"
    " local not for profit Community Action Agency. They work with partners to"
    " administer many programs, including government grants for bills, health care and"
    " more for low income families and the larger community. While most of the"
    " financial aid they offer is in the form of referrals to local Emergency Services"
    " Network Providers, they are still one option to call when struggling.\n",
    "\nEmergency Services consists of short term crisis intervention, such as"
    " rental/mortgage assistance, utility assistance, and other employment or"
    " educational needs. Long term case management is also provided to help in the"
    " stability of vulnerable households.\n",
    "\nThe Salvation Army knows that sometimes life throws you a curve ball. Job loss,"
    " disaster, a medical issue or another crisis can really knock you off your"
    " feet—even if only for a moment. Before you know it, you’re behind on your rent or"
    " utilities, or you can’t buy food or clothes for your family. But The Salvation"
    " Army is here for you. We help you secure necessities to stay in your home and"
    " move past the initial crisis.\n\nBy providing a variety of services to help"
    " families and individuals weather the storm, whether it be financial emergency,"
    " shut-off notices or through a multitude of other hardships, every year we serve"
    " millions of individuals across the United States.\n",
    "\nWe understand our customers sometimes face financial challenges, and when they"
    " do, we are ready to help. Tucson Electric Power's Lifeline program offers an $18"
    " monthly discount for qualifying low-income customers who need help paying their"
    " electric bill.\n\nTEP also works with community partners to provide emergency"
    " bill payment assistance to qualifying customers. In addition to funds contributed"
    " by TEP and our customers, these providers can access federal energy assistance"
    " funds and emergency aid provided through the CARES pandemic relief act approved"
    " earlier this year.\n",
    "\nYouth On Their Own (YOTO) supports the high school graduation and continued"
    " success of youth experiencing homelessness in Pima County. We strive to eliminate"
    " barriers to education and empower housing insecure youth in our community to stay"
    " in school. For over 35 years, we have supported this unique demographic by"
    " providing financial assistance, basic human needs, guidance, and more. With the"
    " help of our amazing YOTO Family, YOTO has supported over 20,000 local youth in"
    " their journeys toward high school graduation!\n",
]
