version: '3.6'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    env_file:
      - .env
    networks:
      - pocas_net

  redis:
    image: docker.io/bitnami/redis:7.0
    volumes:
      - 'redis_data:/bitnami'
    env_file:
      - .env
    networks:
      - pocas_net

  airflow-scheduler:
    container_name: pocas_airflow_scheduler
    image: docker.io/bitnami/airflow-scheduler:2
    env_file:
      - .env
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
    networks:
      - pocas_net


  airflow-worker:
    image: docker.io/bitnami/airflow-worker:2
    container_name: pocas_airflow_worker
    env_file:
      - .env
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
    networks:
      - pocas_net

  airflow:
    image: docker.io/bitnami/airflow:2
    container_name: pocas_airflow
    env_file:
      - .env
    networks:
      - pocas_net
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
    ports:
      - '8080:8080'

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local

networks:
  pocas_net:
    external: true